#!/usr/bin/env bash
# Provision the e2e's own OIDC project, SPA app and login user in the running
# Zitadel, headlessly via the Management API — no UI, no admin sign-in. Uses the
# org-owner service-account PAT that `start-from-init` wrote to the shared
# volume, and writes every created id to ../.e2e-oidc.env so deprovision.sh can
# remove exactly what this run created.
#
# The run owns its identities rather than borrowing the instance admin: that is
# what makes it repeatable and lets it leave nothing behind.
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"

ZITADEL_PORT="${E2E_ZITADEL_PORT:-8080}"
ISSUER="http://localhost:$ZITADEL_PORT"
REDIRECT_URI="${E2E_REDIRECT_URI:-http://localhost:5173/}"
ENV_OUT="$SCRIPT_DIR/../.e2e-oidc.env"

# The operator this run signs in as. The password is a fixture, not a secret:
# the instance is thrown away with the containers.
LOGIN_USERNAME="erun-e2e-operator"
LOGIN_PASSWORD="E2eOperator1!"

VOL="erun-console-e2e-bootstrap"
SA="$(docker run --rm -v "$VOL":/b alpine cat /b/admin-sa.pat)"
[ -n "$SA" ] || {
  echo "admin-sa PAT not found in volume $VOL" >&2
  exit 1
}
auth=(-H "Authorization: Bearer $SA" -H "Content-Type: application/json")

field() { python3 -c "import sys,json;print(json.load(sys.stdin)['$1'])"; }

echo "==> pinning the org login policy (password only: no passkey, no MFA, no registration)"
# Without this the org inherits the instance default, which offers passkey
# enrolment after the password step and would make the sign-in non-deterministic.
# Omitted booleans are proto zero values: forceMfa false, passwordless not allowed.
curl -fsS "${auth[@]}" -X POST "$ISSUER/management/v1/policies/login" -d '{
  "allowUsernamePassword": true,
  "allowRegister": false,
  "allowExternalIdp": false,
  "forceMfa": false,
  "forceMfaLocalOnly": false,
  "passwordlessType": "PASSWORDLESS_TYPE_NOT_ALLOWED",
  "hidePasswordReset": true,
  "allowDomainDiscovery": true,
  "passwordCheckLifetime": "864000s",
  "externalLoginCheckLifetime": "864000s",
  "mfaInitSkipLifetime": "2592000s",
  "secondFactorCheckLifetime": "64800s",
  "multiFactorCheckLifetime": "43200s"
}' >/dev/null

echo "==> creating the project + OIDC SPA app (PKCE, redirect $REDIRECT_URI)"
PROJECT_ID="$(curl -fsS "${auth[@]}" -X POST "$ISSUER/management/v1/projects" \
  -d '{"name":"erun-console-e2e"}' | field id)"

APP_JSON="$(curl -fsS "${auth[@]}" -X POST "$ISSUER/management/v1/projects/$PROJECT_ID/apps/oidc" -d "$(
  cat <<JSON
{
  "name": "erun-console",
  "redirectUris": ["$REDIRECT_URI"],
  "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
  "grantTypes": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
  "appType": "OIDC_APP_TYPE_USER_AGENT",
  "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",
  "postLogoutRedirectUris": ["$REDIRECT_URI"],
  "devMode": true,
  "accessTokenType": "OIDC_TOKEN_TYPE_BEARER"
}
JSON
)")"
APP_ID="$(printf '%s' "$APP_JSON" | field appId)"
CLIENT_ID="$(printf '%s' "$APP_JSON" | field clientId)"

echo "==> creating the login user $LOGIN_USERNAME"
# _import (not /users/human) is the endpoint that takes a password and can clear
# passwordChangeRequired, so the first sign-in is not a forced password change.
USER_ID="$(curl -fsS "${auth[@]}" -X POST "$ISSUER/management/v1/users/human/_import" -d "$(
  cat <<JSON
{
  "userName": "$LOGIN_USERNAME",
  "profile": {"firstName": "Erun", "lastName": "Operator", "preferredLanguage": "en"},
  "email": {"email": "$LOGIN_USERNAME@erun.local", "isEmailVerified": true},
  "password": "$LOGIN_PASSWORD",
  "passwordChangeRequired": false
}
JSON
)" | field userId)"

# The domain policy may append the org's primary domain to the username, so the
# loginName the sign-in page expects is read back rather than assumed.
LOGIN_NAME="$(curl -fsS "${auth[@]}" "$ISSUER/management/v1/users/$USER_ID" \
  | python3 -c 'import sys,json;print(json.load(sys.stdin)["user"]["preferredLoginName"])')"

cat >"$ENV_OUT" <<ENV
# Generated by zitadel/provision.sh — do not edit.
export E2E_OIDC_ISSUER="$ISSUER"
export E2E_OIDC_CLIENT_ID="$CLIENT_ID"
export E2E_OIDC_PROJECT_ID="$PROJECT_ID"
export E2E_OIDC_APP_ID="$APP_ID"
export E2E_OIDC_USER_ID="$USER_ID"
export E2E_LOGIN_NAME="$LOGIN_NAME"
export E2E_LOGIN_PASSWORD="$LOGIN_PASSWORD"
ENV

echo "==> provisioned: project=$PROJECT_ID app=$APP_ID client_id=$CLIENT_ID login=$LOGIN_NAME"
