#!/usr/bin/env bash
# Bring up the local Zitadel v4 (core + Login V2 + proxy), then provision the
# console's OIDC SPA app headlessly via the Management API — using the org-owner
# service-account PAT that `start-from-init` wrote to the shared volume. Writes
# the resulting issuer / client id / admin credentials to ../.e2e-oidc.env for
# run.sh to source. No UI, no admin login: the whole bootstrap is API-driven.
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

ISSUER="http://localhost:8080"
REDIRECT_URI="${E2E_REDIRECT_URI:-http://localhost:5173/}"
ENV_OUT="$SCRIPT_DIR/../.e2e-oidc.env"

echo "==> bringing up Zitadel (core + login + proxy)"
docker compose up -d

echo "==> waiting for zitadel-api + zitadel-login to be healthy"
for _ in $(seq 1 90); do
  api="$(docker inspect -f '{{.State.Health.Status}}' erun-console-zitadel-zitadel-api-1 2>/dev/null || echo missing)"
  login="$(docker inspect -f '{{.State.Health.Status}}' erun-console-zitadel-zitadel-login-1 2>/dev/null || echo missing)"
  [ "$api" = healthy ] && [ "$login" = healthy ] && break
  sleep 3
done
[ "$api" = healthy ] && [ "$login" = healthy ] || { echo "zitadel did not become healthy (api=$api login=$login)"; exit 1; }

echo "==> reading the org-owner service-account PAT from the bootstrap volume"
VOL="$(docker volume ls --format '{{.Name}}' | grep -E 'erun-console-zitadel.*bootstrap' | head -1)"
SA="$(docker run --rm -v "$VOL":/b alpine cat /b/admin-sa.pat)"
[ -n "$SA" ] || { echo "admin-sa PAT not found"; exit 1; }

auth=(-H "Authorization: Bearer $SA" -H "Content-Type: application/json")

echo "==> creating project + OIDC SPA app (PKCE)"
PID="$(curl -fsS "${auth[@]}" -X POST "$ISSUER/management/v1/projects" \
  -d '{"name":"erun-console-project"}' | python3 -c 'import sys,json;print(json.load(sys.stdin)["id"])')"

CLIENT_ID="$(curl -fsS "${auth[@]}" -X POST "$ISSUER/management/v1/projects/$PID/apps/oidc" -d "$(cat <<JSON
{
  "name": "erun-console",
  "redirectUris": ["$REDIRECT_URI"],
  "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
  "grantTypes": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
  "appType": "OIDC_APP_TYPE_USER_AGENT",
  "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",
  "postLogoutRedirectUris": ["$REDIRECT_URI"],
  "devMode": true,
  "accessTokenType": "OIDC_TOKEN_TYPE_BEARER"
}
JSON
)" | python3 -c 'import sys,json;print(json.load(sys.stdin)["clientId"])')"
[ -n "$CLIENT_ID" ] || { echo "OIDC app creation failed"; exit 1; }

# The first-instance human admin's loginName. Zitadel's domain policy appends
# the org's primary domain to the username (zadmin -> zadmin@erun.localhost), so
# we pick the one human loginName (it carries an "@"; the machine users —
# login-client, admin-sa — do not).
LOGIN_NAME="$(curl -fsS "${auth[@]}" -X POST "$ISSUER/management/v1/users/_search" -d '{}' \
  | python3 -c 'import sys,json;print(next(ln for u in json.load(sys.stdin)["result"] for ln in u.get("loginNames",[]) if "@" in ln))')"

cat > "$ENV_OUT" <<ENV
# Generated by zitadel/provision.sh — do not edit.
export E2E_OIDC_ISSUER="$ISSUER"
export E2E_OIDC_CLIENT_ID="$CLIENT_ID"
export E2E_LOGIN_NAME="$LOGIN_NAME"
export E2E_LOGIN_PASSWORD="Password1!"
ENV

echo "==> provisioned: client_id=$CLIENT_ID login=$LOGIN_NAME"
echo "==> wrote $ENV_OUT"
