environments:
    local:
        containerregistry: ghcr.io/sophium
        docker:
            fingerprints:
                erun-ubuntu: 6ffef71a59498123
        k8s:
            deployments:
                - [erun-devops, erun-backend-postgres]
                - erun-backend-db
                - erun-backend-api
