apiVersion: v2
appVersion: 1.0.269-pr.7c1372db
description: ERun hosted OCI container registry (zot), authenticated by tenant API token
name: erun-oci-registry
type: application
version: 1.0.269-pr.7c1372db
