apiVersion: v2
appVersion: 1.0.261-pr.4d07804a
description: ERun hosted OCI container registry (zot), authenticated by tenant API token
name: erun-oci-registry
type: application
version: 1.0.261-pr.4d07804a
