-- A persisted, sequenced log of a tenant's environment events, so a reader
-- can resume from the position it last reached rather than re-fetch a read
-- model and guess what changed.
--
-- Hand-written (atlas migrate diff is login-gated on the RLS functions in the
-- source schema); mirrors schema/tables/environment_events.sql,
-- schema/indexes/environment_events.sql, schema/rls/environment_events.sql,
-- schema/triggers/timestamps.sql, and schema/roles.sql.

CREATE TABLE "environment_events" (
  "environment_event_id" uuid NOT NULL DEFAULT uuidv7(),
  "environment_event_seq" bigint GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" uuid NOT NULL DEFAULT erun_current_tenant_id(),
  "environment_id" uuid NOT NULL,
  "kind" text NOT NULL,
  "detail" text NULL,
  "occurred_at" timestamptz NOT NULL DEFAULT NOW(),
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  PRIMARY KEY ("environment_event_id"),
  CONSTRAINT "environment_events_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("tenant_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "environment_events_tenant_environment_fkey" FOREIGN KEY ("tenant_id", "environment_id") REFERENCES "environments" ("tenant_id", "environment_id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "environment_events_kind_check" CHECK ("kind" IN ('environment-status-changed', 'session-awaiting-input', 'job-finished')),
  CONSTRAINT "environment_events_tenant_event_key" UNIQUE ("tenant_id", "environment_event_id"),
  CONSTRAINT "environment_events_tenant_seq_key" UNIQUE ("tenant_id", "environment_event_seq")
);

CREATE INDEX "environment_events_tenant_environment_seq_idx"
  ON "environment_events" ("tenant_id", "environment_id", "environment_event_seq");

CREATE TRIGGER "environment_events_set_timestamps"
  BEFORE INSERT OR UPDATE ON "environment_events"
  FOR EACH ROW
  EXECUTE FUNCTION erun_set_timestamps();

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES
  ON "environment_events"
  TO erun_tenant, erun_operations;

ALTER TABLE "environment_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "environment_events" FORCE ROW LEVEL SECURITY;

CREATE POLICY environment_events_tenant_isolation
  ON "environment_events"
  FOR ALL
  TO erun_tenant
  USING (tenant_id = erun_current_tenant_id())
  WITH CHECK (tenant_id = erun_current_tenant_id());

CREATE POLICY environment_events_operations_access
  ON "environment_events"
  FOR ALL
  TO erun_operations
  USING (true)
  WITH CHECK (true);
