import { createSelector } from '@reduxjs/toolkit';

import type { AppState } from './state';
import type { RootState } from './store';

export const selectActivityLocks = (state: RootState) => state.activity.locksBySession;

// Components read the legacy AppState shape via useControllerState. The shape
// is reassembled from the discrete slices so consumers do not have to change
// while ERunUIController moves toward dispatch-only writes. createSelector
// memoizes the result so React re-renders only when an input slice changes.
export const selectAppState = createSelector(
  [
    (state: RootState) => state.selection.selected,
    (state: RootState) => state.tenants.tenants,
    (state: RootState) => state.tenants.cloudProviders,
    (state: RootState) => state.tenants.versionSuggestions,
    (state: RootState) => state.environmentDialog,
    (state: RootState) => state.manageDialog,
    (state: RootState) => state.tenantDialog,
    (state: RootState) => state.tenantDashboard,
    (state: RootState) => state.globalConfigDialog,
    (state: RootState) => state.sidebar.collapsedTenants,
    (state: RootState) => state.terminal.sessionId,
    (state: RootState) => state.terminal.tabsByEnv,
    (state: RootState) => state.terminal.selectedSessionByEnv,
    (state: RootState) => state.terminal.debugOutput,
    (state: RootState) => state.layout,
    (state: RootState) => state.review,
    (state: RootState) => state.notification.notification,
    (state: RootState) => state.terminalStatus,
    (state: RootState) => state.idle.idleStatus,
    (state: RootState) => state.idle.idleCloudContextBusy,
    (state: RootState) => state.sidebar.sidebarCloudAliasBusy,
    (state: RootState) => state.sidebar.sidebarCloudAliasAction,
    (state: RootState) => state.doctor.lastDoctorBySelection,
  ],
  (
    selected,
    tenants,
    cloudProviders,
    versionSuggestions,
    environmentDialog,
    manageDialog,
    tenantDialog,
    tenantDashboard,
    globalConfigDialog,
    collapsedTenants,
    sessionId,
    tabsByEnv,
    selectedSessionByEnv,
    debugOutput,
    layout,
    review,
    notification,
    terminalStatus,
    idleStatus,
    idleCloudContextBusy,
    sidebarCloudAliasBusy,
    sidebarCloudAliasAction,
    lastDoctorBySelection,
  ): AppState => ({
    tenants,
    cloudProviders,
    selected,
    versionSuggestions,
    environmentDialog,
    manageDialog,
    tenantDialog,
    tenantDashboard,
    globalConfigDialog,
    collapsedTenants: new Set(collapsedTenants),
    sessionId,
    tabsByEnv,
    selectedSessionByEnv,
    sidebarWidth: layout.sidebarWidth,
    reviewWidth: layout.reviewWidth,
    filesWidth: layout.filesWidth,
    filesOpen: layout.filesOpen,
    sidebarHidden: layout.sidebarHidden,
    reviewOpen: layout.reviewOpen,
    changedFilesOpen: layout.changedFilesOpen,
    diff: review.diff,
    diffLoading: review.diffLoading,
    diffError: review.diffError,
    diffErrorReconnectable: review.diffErrorReconnectable,
    reconnect: review.reconnect,
    selectedDiffPath: review.selectedDiffPath,
    selectedReviewScope: review.selectedReviewScope,
    selectedReviewCommit: review.selectedReviewCommit,
    diffFilter: review.diffFilter,
    collapsedDiffDirs: new Set(review.collapsedDiffDirs),
    notification,
    terminalMessage: terminalStatus.terminalMessage,
    terminalStatusKind: terminalStatus.terminalStatusKind,
    terminalStatusDetail: terminalStatus.terminalStatusDetail,
    terminalStatusAction: terminalStatus.terminalStatusAction,
    terminalBusy: terminalStatus.terminalBusy,
    terminalCopyOutput: terminalStatus.terminalCopyOutput,
    terminalCopyStatus: terminalStatus.terminalCopyStatus,
    idleStatus,
    idleCloudContextBusy,
    sidebarCloudAliasBusy,
    sidebarCloudAliasAction,
    debugOpen: layout.debugOpen,
    debugHeight: layout.debugHeight,
    debugOutput,
    lastDoctorBySelection,
  }),
);
