// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function ResizeSession(arg1, arg2) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2);
}

export function SendSessionInput(arg1) {
  return window['go']['main']['App']['SendSessionInput'](arg1);
}

export function StartSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSession'](arg1, arg2, arg3);
}
