// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadState():Promise<main.uiState>;

export function ResizeSession(arg1:number,arg2:number):Promise<void>;

export function SendSessionInput(arg1:string):Promise<void>;

export function StartSession(arg1:main.uiSelection,arg2:number,arg3:number):Promise<main.startSessionResult>;
