version: 2

run:
  timeout: 3m
  tests: true
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
formatters:
  enable:
    - gofumpt
formatters-settings:
  gofumpt:
    module-path: github.com/sophium/erun
issues:
  exclude-use-default: false
