package eruncommon

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestEnsureDefaultDevopsChartBakesAppVersionIntoChartYAML locks the
// generator side of issue #361: the materialized tenant Chart.yaml
// must carry the resolved appVersion, not the asset's literal
// placeholder. Helm reads `.Chart.AppVersion` for the runtime image
// tags (erun-mcp, <tenant>-devops, …), so a stale placeholder pins
// every tenant to a non-existent or year-old image.
func TestEnsureDefaultDevopsChartBakesAppVersionIntoChartYAML(t *testing.T) {
	projectRoot := t.TempDir()
	if err := EnsureDefaultDevopsChartWithVersion(Context{}, projectRoot, "tenant-a", DefaultEnvironment, "1.0.75"); err != nil {
		t.Fatalf("EnsureDefaultDevopsChartWithVersion failed: %v", err)
	}
	moduleName := RuntimeReleaseName("tenant-a")
	chartPath := filepath.Join(projectRoot, moduleName, "k8s", moduleName, "Chart.yaml")
	data, err := os.ReadFile(chartPath)
	if err != nil {
		t.Fatalf("read generated Chart.yaml: %v", err)
	}
	content := string(data)
	if strings.Contains(content, "__APP_VERSION__") {
		t.Fatalf("placeholder leaked into generated Chart.yaml:\n%s", content)
	}
	for _, want := range []string{
		`version: "1.0.75"`,
		`appVersion: "1.0.75"`,
	} {
		if !strings.Contains(content, want) {
			t.Fatalf("expected %q in generated Chart.yaml:\n%s", want, content)
		}
	}
}

// TestEnsureDefaultDevopsChartFallsBackToDevWhenAppVersionUnset
// guards the empty-version path: callers that resolved no runtime
// version (e.g. open without an env override and a "dev" binary)
// must still produce a valid Chart.yaml without leaking the
// __APP_VERSION__ placeholder into helm renders.
func TestEnsureDefaultDevopsChartFallsBackToDevWhenAppVersionUnset(t *testing.T) {
	projectRoot := t.TempDir()
	if err := EnsureDefaultDevopsChart(Context{}, projectRoot, "tenant-a", DefaultEnvironment); err != nil {
		t.Fatalf("EnsureDefaultDevopsChart failed: %v", err)
	}
	moduleName := RuntimeReleaseName("tenant-a")
	chartPath := filepath.Join(projectRoot, moduleName, "k8s", moduleName, "Chart.yaml")
	data, err := os.ReadFile(chartPath)
	if err != nil {
		t.Fatalf("read generated Chart.yaml: %v", err)
	}
	content := string(data)
	if strings.Contains(content, "__APP_VERSION__") {
		t.Fatalf("placeholder leaked into generated Chart.yaml:\n%s", content)
	}
	if !strings.Contains(content, `appVersion: "dev"`) {
		t.Fatalf("expected dev fallback in generated Chart.yaml:\n%s", content)
	}
}

// TestEnsureDefaultDevopsChartUpgradesLegacyAppVersionOnDisk locks
// the migration path for existing tenant charts. A user whose
// `<tenant>-devops/k8s/<tenant>-devops/Chart.yaml` was generated by
// an older binary still carries `appVersion: "1.0.0"` and the helm
// renders point at non-existent images. The next
// EnsureDefaultDevopsChartWithVersion call must rewrite that file
// in place; non-devops Chart.yaml files (backend-* siblings) must
// stay untouched so this migration cannot accidentally clobber a
// modified tenant chart.
func TestEnsureDefaultDevopsChartUpgradesLegacyAppVersionOnDisk(t *testing.T) {
	projectRoot := t.TempDir()
	moduleName := RuntimeReleaseName("tenant-a")
	chartPath := filepath.Join(projectRoot, moduleName, "k8s", moduleName, "Chart.yaml")
	if err := os.MkdirAll(filepath.Dir(chartPath), 0o755); err != nil {
		t.Fatalf("mkdir Chart.yaml dir: %v", err)
	}
	legacy := "apiVersion: v2\nname: " + moduleName + "\ndescription: ERun DevOps\ntype: application\nversion: \"1.0.0\"\nappVersion: \"1.0.0\"\n"
	if err := os.WriteFile(chartPath, []byte(legacy), 0o644); err != nil {
		t.Fatalf("write legacy Chart.yaml: %v", err)
	}

	if err := EnsureDefaultDevopsChartWithVersion(Context{}, projectRoot, "tenant-a", DefaultEnvironment, "1.0.75"); err != nil {
		t.Fatalf("EnsureDefaultDevopsChartWithVersion failed: %v", err)
	}

	got, err := os.ReadFile(chartPath)
	if err != nil {
		t.Fatalf("read upgraded Chart.yaml: %v", err)
	}
	for _, want := range []string{
		`version: "1.0.75"`,
		`appVersion: "1.0.75"`,
	} {
		if !strings.Contains(string(got), want) {
			t.Fatalf("expected %q after upgrade, got:\n%s", want, got)
		}
	}
}

// TestEnsureDefaultDevopsChartPreservesModifiedChartYAML keeps the
// upgrade narrow: only the exact pre-#361 placeholder-pinned shape
// is rewritten. A tenant who hand-edited their Chart.yaml — bumped
// the version themselves, added a maintainer field, changed the
// description — must not have their changes clobbered by the
// migration.
func TestEnsureDefaultDevopsChartPreservesModifiedChartYAML(t *testing.T) {
	projectRoot := t.TempDir()
	moduleName := RuntimeReleaseName("tenant-a")
	chartPath := filepath.Join(projectRoot, moduleName, "k8s", moduleName, "Chart.yaml")
	if err := os.MkdirAll(filepath.Dir(chartPath), 0o755); err != nil {
		t.Fatalf("mkdir Chart.yaml dir: %v", err)
	}
	modified := "apiVersion: v2\nname: " + moduleName + "\ndescription: ERun DevOps\ntype: application\nversion: \"1.0.0\"\nappVersion: \"1.0.0\"\nmaintainers:\n  - name: tenant-team\n"
	if err := os.WriteFile(chartPath, []byte(modified), 0o644); err != nil {
		t.Fatalf("write modified Chart.yaml: %v", err)
	}

	if err := EnsureDefaultDevopsChartWithVersion(Context{}, projectRoot, "tenant-a", DefaultEnvironment, "1.0.75"); err != nil {
		t.Fatalf("EnsureDefaultDevopsChartWithVersion failed: %v", err)
	}

	got, err := os.ReadFile(chartPath)
	if err != nil {
		t.Fatalf("read Chart.yaml: %v", err)
	}
	if string(got) != modified {
		t.Fatalf("expected modified Chart.yaml to be preserved, got:\n%s", got)
	}
}

// TestEnsureDefaultDevopsChartDoesNotTouchSiblingBackendCharts is
// the safety check that the legacy upgrade is scoped by `description:
// ERun DevOps`. The default tenant tree also lays down backend-api /
// backend-db / backend-postgres charts whose Chart.yaml files share
// the base name; rewriting those by mistake would silently flip
// images for unrelated services.
func TestEnsureDefaultDevopsChartDoesNotTouchSiblingBackendCharts(t *testing.T) {
	projectRoot := t.TempDir()
	moduleName := RuntimeReleaseName("tenant-a")
	backendChart := filepath.Join(projectRoot, moduleName, "k8s", "erun-backend-api", "Chart.yaml")
	if err := os.MkdirAll(filepath.Dir(backendChart), 0o755); err != nil {
		t.Fatalf("mkdir backend chart dir: %v", err)
	}
	original := "apiVersion: v2\nname: erun-backend-api\ndescription: ERun backend API\ntype: application\nversion: \"1.0.0\"\nappVersion: \"1.0.0\"\n"
	if err := os.WriteFile(backendChart, []byte(original), 0o644); err != nil {
		t.Fatalf("write backend Chart.yaml: %v", err)
	}

	if err := EnsureDefaultDevopsChartWithVersion(Context{}, projectRoot, "tenant-a", DefaultEnvironment, "1.0.75"); err != nil {
		t.Fatalf("EnsureDefaultDevopsChartWithVersion failed: %v", err)
	}

	got, err := os.ReadFile(backendChart)
	if err != nil {
		t.Fatalf("read backend Chart.yaml: %v", err)
	}
	if string(got) != original {
		t.Fatalf("backend Chart.yaml was rewritten by the devops migration; got:\n%s", got)
	}
}
