#!/usr/bin/env sh
# Bake the offline Terraform provider mirror that the erun-devops image test
# stage runs `make check`'s terraform-module-tests target against.
#
#   terraform-providers-mirror.sh [root] [linux-platform-arch]
#
# Defaults: root /opt/terraform-providers, arch amd64. The root receives the
# mirror itself under `mirror/` and the CLI config that points at it as
# `terraform.tfrc`; keeping them in one directory means the image sets exactly
# one path (TF_CLI_CONFIG_FILE) and the mirror location is recorded where the
# config can be read, not duplicated into it by hand.
#
# Why a baked mirror rather than letting the gate fetch providers itself:
# `terraform init` against registry.terraform.io is a ~40MB network dependency
# inside `make check-gate`, and a suite that goes red because a registry was
# slow or unreachable is a false-red gate -- the failure mode a whole change
# was spent removing from lint's timeout. Baking the providers at image
# build moves that dependency to the one place this Dockerfile is already
# network-dependent (helm, atlas, node, Playwright's browser deps) and leaves
# the gate itself with no terraform network path at all: the generated CLI
# config below sends every registry.terraform.io provider to the mirror and
# excludes `direct` for them, so a provider missing from the mirror fails
# loudly here rather than silently falling back to a fetch.
#
# The mirror is built by running `terraform providers mirror` in each module
# that has tests, which honours that module's committed
# `.terraform.lock.hcl` ("Selected v2.17.0 to match dependency lock file"), so
# the mirror cannot disagree with the pin the gate initializes against. A
# provider bump is therefore one reviewed edit -- versions.tf, then
# `terraform providers lock`, both committed -- and the next image build
# mirrors the new set automatically. The module list comes from
# scripts/terraform-test-modules.sh, the same rule the Makefile target and the
# structural test read.
#
# The cache directory is separate from the destination on purpose: the caller
# mounts it as a BuildKit cache, so a rebuild whose only change is module
# source re-copies ~40MB locally instead of re-downloading it.
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root=$(CDPATH= cd -- "${script_dir}/.." && pwd)

dest=${1:-/opt/terraform-providers}
arch=${2:-amd64}
cache=${TERRAFORM_PROVIDER_CACHE_DIR:-/root/.cache/terraform-providers}

command -v terraform >/dev/null 2>&1 || {
	echo "terraform-providers-mirror: no terraform on PATH; the image test stage installs it from TERRAFORM_VERSION before this runs" >&2
	exit 1
}

mkdir -p "${cache}"

# `-platform` is explicit rather than implied so the bake is reproducible on
# whatever host happens to build the image; the caller passes the build arch,
# matching how helm and atlas are installed in the same stage.
modules=$(sh "${script_dir}/terraform-test-modules.sh")
for module in ${modules}; do
	printf 'terraform-providers-mirror: mirroring providers for %s\n' "${module}"
	( cd "${root}/${module}" && terraform providers mirror -platform="linux_${arch}" "${cache}" )
done

# Replaced rather than merged so a provider dropped from the lock files does
# not linger in the image and quietly satisfy an init that should have failed.
mirror="${dest}/mirror"
rm -rf "${mirror}"
mkdir -p "${mirror}"
cp -a "${cache}/." "${mirror}/"

cat >"${dest}/terraform.tfrc" <<EOF
# Generated by scripts/terraform-providers-mirror.sh. See that script for why
# the gate is given no registry path for registry.terraform.io providers.
provider_installation {
  filesystem_mirror {
    path    = "${mirror}"
    include = ["registry.terraform.io/*/*"]
  }
  direct {
    exclude = ["registry.terraform.io/*/*"]
  }
}
EOF

printf 'terraform-providers-mirror: wrote %s and %s\n' "${mirror}" "${dest}/terraform.tfrc"
