ARG ERUN_VERSION=1.0.0

FROM ghcr.io/rihards-freimanis/erun-devops:${ERUN_VERSION}

LABEL org.opencontainers.image.source=https://github.com/sophium/erun

ENTRYPOINT ["erun-devops-entrypoint"]
CMD ["api"]
