-- An append-only, sequenced log of what happened to a tenant's environments:
-- one row per event a producer actually reported, never rewritten. Its job is
-- to be resumable -- a reader that lost its connection names the position it
-- last reached and gets everything after it, in order, which a read model it
-- re-fetches cannot express and a newest-first page cannot serve in order.
--
-- environment_event_seq is that position. It is a database-assigned monotonic
-- integer, deliberately not the API-visible id: the cursor has to compare and
-- order by position alone, and neither a timestamp (collides within a
-- millisecond) nor a uuidv7 (random tail inside one) gives a stable total
-- order on its own.
CREATE TABLE environment_events (
  environment_event_id UUID PRIMARY KEY DEFAULT uuidv7(),
  environment_event_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id UUID NOT NULL DEFAULT erun_current_tenant_id(),
  environment_id UUID NOT NULL,
  -- kind is a closed vocabulary on purpose: an event kind exists once
  -- something real reports it, so the log cannot fill with kinds nothing
  -- produces or reads.
  kind TEXT NOT NULL,
  -- detail carries the event's own payload as serialized text (compact JSON
  -- for structured input), the shape audit_events.api_parameters already
  -- stores. Deliberately uninterpreted: what a kind carries is that kind's
  -- business, not the log's.
  detail TEXT,
  -- occurred_at is when the producer observed the event, supplied by the
  -- reporter (defaulted to the platform's clock when it has none); created_at
  -- is trigger-owned record time. A report can arrive after the fact, so the
  -- two answer different questions.
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id),
  -- Cascades with the environment: an event describing a deleted environment
  -- describes nothing a reader can act on, unlike usage_events' own
  -- environment_id FK, which is deliberately SET NULL to keep an append-only
  -- metering trail alive past the row it described.
  CONSTRAINT environment_events_tenant_environment_fkey FOREIGN KEY (tenant_id, environment_id) REFERENCES environments (tenant_id, environment_id) ON DELETE CASCADE,
  CONSTRAINT environment_events_kind_check CHECK (kind IN ('environment-status-changed', 'session-awaiting-input', 'job-finished')),
  CONSTRAINT environment_events_tenant_event_key UNIQUE (tenant_id, environment_event_id),
  -- The cursor read's own index: a tenant's log walked in sequence order. It
  -- is a uniqueness contract as well as an index because the sequence is
  -- global, so two tenants can never collide on one position.
  CONSTRAINT environment_events_tenant_seq_key UNIQUE (tenant_id, environment_event_seq)
);
