CREATE TABLE environments (
  environment_id UUID PRIMARY KEY DEFAULT uuidv7(),
  tenant_id UUID NOT NULL DEFAULT erun_current_tenant_id(),
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  kubernetes_context TEXT,
  context_id UUID,
  runtime_version TEXT,
  status TEXT NOT NULL DEFAULT 'registered',
  provision_error TEXT,
  deployed_version TEXT,
  expose_error TEXT,
  exposed_hostname TEXT,
  delete_error TEXT,
  delete_attempts INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  FOREIGN KEY (tenant_id) REFERENCES tenants (tenant_id),
  FOREIGN KEY (tenant_id, context_id) REFERENCES contexts (tenant_id, context_id),
  CONSTRAINT environments_name_check CHECK (length(trim(name)) > 0),
  CONSTRAINT environments_type_check CHECK (type IN ('local-agent', 'remote-agent', 'runtime')),
  CONSTRAINT environments_status_check CHECK (status IN ('registered', 'provisioning', 'running', 'failed', 'deleting', 'deletion-blocked')),
  CONSTRAINT environments_tenant_environment_key UNIQUE (tenant_id, environment_id),
  CONSTRAINT environments_tenant_name_key UNIQUE (tenant_id, name)
);
